import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseTokens,splitDeclarations,categoryOf,contrast,contrastGrade,safeValue,restoreOverrides,exportCSS,filterTokens,propertyFor} from '../design-system/src/tokens.mjs';
import {button,escapeHTML} from '../src/components.mjs';
const source=await readFile(new URL('../src/tokens.css',import.meta.url),'utf8');
const tokens=parseTokens(source);
test('source has 63 unique original token declarations',()=>{assert.equal(tokens.length,63);assert.equal(new Set(tokens.map(t=>t.name)).size,63);});
test('primary brand value matches recovered source',()=>assert.equal(tokens.find(t=>t.name==='--color-brand').value,'#315dff'));
test('all seven foundations are represented',()=>assert.equal(new Set(tokens.map(t=>t.category)).size,7));
test('font lists and motion functions retain all punctuation',()=>{assert.ok(tokens.find(t=>t.name==='--font-sans').value.includes('"Noto Sans CJK SC"'));assert.equal(tokens.find(t=>t.name==='--ease-standard').value,'cubic-bezier(.2,.8,.2,1)');});
test('split declarations respects semicolons inside strings',()=>assert.equal(splitDeclarations('--font-a: "a;b"; --test: rgb(1 2 3 / 40%);').length,2));
test('repeated :root token overrides take the final declaration',()=>assert.equal(parseTokens(':root{--a:1px}:root{--a:2px}')[0].value,'2px'));
test('comments and non-root declarations are ignored',()=>{const result=parseTokens('/* --a: xxx; */ :root { --a: 1px; } .other { --b: 2px; }');assert.equal(result.length,1);});
test('invalid or empty source fails clearly',()=>{assert.throws(()=>parseTokens('.a { --b: 2px; }'));assert.throws(()=>parseTokens(':root{}'));});
test('every kind gets a valid preview property',()=>{assert.equal(categoryOf('--focus-ring'),'elevation');assert.equal(propertyFor('--focus-ring'),'box-shadow');assert.equal(propertyFor('--duration-fast'),'transition-duration');assert.equal(propertyFor('--sidebar-width'),'width');});
test('full source export roundtrips names and values',()=>assert.deepEqual(parseTokens(exportCSS(tokens)),tokens));
test('export applies drafts without mutating source',()=>{const changed=exportCSS(tokens,{'--color-brand':'#6d28d9'});assert.equal(parseTokens(changed).find(t=>t.name==='--color-brand').value,'#6d28d9');assert.equal(tokens.find(t=>t.name==='--color-brand').value,'#315dff');});
test('contrast gives black/white 21 and same-color 1',()=>{assert.equal(contrast('#000','#fff'),21);assert.equal(contrast('#315dff','#315dff'),1);});
test('contrast is symmetric and rejects unsupported color encodings',()=>{assert.equal(contrast('#123456','#abcdef'),contrast('#abcdef','#123456'));assert.equal(contrast('rgba(0,0,0,.5)','#fff'),null);});
test('contrast thresholds use unrounded ratios',()=>{assert.equal(contrastGrade(4.49999),'Large text only');assert.equal(contrastGrade(4.5),'AA');assert.equal(contrastGrade(7),'AAA');});
test('unsafe CSS text, URLs, and declarations are rejected',()=>{for(const value of ['red; background:blue','url(https://example.com)','red!important','<script>','', 'red} body {'])assert.equal(safeValue(value),false);});
test('legitimate shadows and font lists are safe',()=>{assert.ok(safeValue('0 2px 6px rgb(0 0 0 / 15%)'));assert.ok(safeValue('"Inter", sans-serif'));});
test('restoring drafts ignores unknown and invalid entries',()=>{assert.deepEqual(restoreOverrides({'--missing':'red','--color-brand':'url(x)','--space-1':'6px'},tokens),{'--space-1':'6px'});});
test('identical source drafts and malformed data are discarded',()=>{assert.deepEqual(restoreOverrides({'--color-brand':'#315dff'},tokens),{});assert.deepEqual(restoreOverrides([],tokens),{});assert.deepEqual(restoreOverrides(null,tokens),{});});
test('browser CSS support callback can reject semantic errors',()=>assert.deepEqual(restoreOverrides({'--color-brand':'123px'},tokens,()=>false),{}));
test('search matches names, friendly labels, and values',()=>{assert.ok(filterTokens(tokens,'brand').length>=5);assert.ok(filterTokens(tokens,'16px').some(t=>t.name==='--space-4'));assert.equal(filterTokens(tokens,'brand','spacing').length,0);});
test('new source declarations are discoverable without a hardcoded catalog',()=>{const more=parseTokens(source+'\n:root{--color-new-test:#112233;}');assert.equal(more.length,64);assert.equal(more.at(-1).category,'colors');});
test('shared components escape content and suppress loading clicks',()=>{assert.ok(button('<script>').includes('&lt;script&gt;'));assert.ok(button('Run',{loading:true}).includes('disabled'));assert.ok(button('Run',{loading:true}).includes('aria-busy="true"'));assert.equal(escapeHTML('"&'),'&quot;&amp;');});
