import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {STORAGE_KEY,shareReportToken,readSharedReport,METRICS,emptyState,createSnapshot,calculateScenario,normalizeState,loadState,saveState,parseMetricInput,publicText,createReport} from '../src/ui-state.mjs';
import {reportHtml} from '../src/ui-report.mjs';
const values={gmv:1000000,conversion:5,engagement:1234,roi:4,repeat:25,live:600,revenue:800000};
const baseline=()=>createSnapshot('订单汇总','2026年9月',values,'2026-09-18T00:00:00.000Z');
const store=()=>{let value=null;return {getItem:k=>value,setItem:(k,v)=>{assert.equal(k,STORAGE_KEY);value=v;}};};
test('all UI modules parse; existing tests may not omit the new entry point',()=>{for(const f of ['ui-state','ui-runtime','ui-report','ui-surfaces'])assert.equal(spawnSync(process.execPath,['--check','src/'+f+'.mjs']).status,0,f);});
test('empty workspace never invents observed or scenario records',()=>{assert.equal(emptyState().snapshot,null);assert.deepEqual(emptyState().scenarios,[]);assert.equal(loadState(store()).state.snapshot,null);});
for(const key of Object.keys(METRICS)){
 test(key+' rejects blank, negative, NaN, infinite and out-of-range input',()=>{for(const v of ['', ' ','NaN','Infinity','-1',String(METRICS[key].max+1)])assert.throws(()=>parseMetricInput(v,key),undefined,v);assert.equal(parseMetricInput('0',key),0);});
}
test('count metrics reject fractions',()=>{assert.throws(()=>parseMetricInput('1.1','engagement'));assert.throws(()=>parseMetricInput('1.1','live'));});
test('persistence round trip is exact and manual cannot claim verification',()=>{let s=store(),b=baseline();b.status='verified';b.provider='Production';b.debug='do not show';const saved=saveState(s,{...emptyState(),snapshot:b});assert.equal(saved.snapshot.status,'unverified');assert.equal(saved.snapshot.sourceType,'manual');assert.ok(!('debug' in saved.snapshot));assert.ok(!('provider' in saved.snapshot));assert.deepEqual(loadState(s).state,saved);});
test('corrupt and blocked reads produce an empty error state, not example fallback',()=>{for(const storage of [{getItem:()=>'{bad'},{getItem:()=>JSON.stringify({schemaVersion:900})},{getItem(){throw Error('private error');}}]){const r=loadState(storage);assert.equal(r.state.snapshot,null);assert.equal(r.error,'read-failed');}});
test('failed persistence throws and leaves the prior state unchanged',()=>{const b=baseline(),initial={...emptyState(),snapshot:b},copy=structuredClone(initial);assert.throws(()=>saveState({setItem(){throw Error('quota');}},initial),{code:'save-failed'});assert.deepEqual(initial,copy);});
test('model requires baseline and validates real inputs',()=>{assert.throws(()=>calculateScenario(null,'ad_efficiency',20,'test'));for(const x of [NaN,Infinity,-100,101])assert.throws(()=>calculateScenario(baseline(),'ad_efficiency',x,'test'));assert.throws(()=>calculateScenario(baseline(),'unknown',20,'test'));assert.throws(()=>calculateScenario(baseline(),'ad_efficiency',20,' '));});
test('lever-specific model preserves baseline and unrelated metrics',()=>{for(const [lever,key,e] of [['ad_efficiency','roi',.35],['checkout_conversion','conversion',1],['content_engagement','engagement',.25],['repeat_purchase','repeat',.4]]){const b=baseline(),copy=structuredClone(b),r=calculateScenario(b,lever,20,'策略比较');assert.deepEqual(b,copy);assert.notStrictEqual(r.baseline,b);assert.equal(r.modeled.gmv,Math.round(values.gmv*(1+.2*e)*100)/100);for(const k of Object.keys(values))if(k!=='gmv'&&k!==key)assert.equal(r.modeled[k],values[k]);assert.equal(r.status,'simulated');assert.equal(r.assumptions.length,2);}});
test('model cannot output impossible percentages',()=>{const b=baseline();b.metrics.conversion=90;assert.throws(()=>calculateScenario(b,'checkout_conversion',50,'test'));});
test('stored scenario output tampering is rejected',()=>{const r=calculateScenario(baseline(),'ad_efficiency',20,'test');r.modeled.gmv+=1;assert.throws(()=>normalizeState({...emptyState(),scenarios:[r]}));});
test('report freezes the run baseline, separate note, and selected identity',()=>{const b=baseline(),r=calculateScenario(b,'ad_efficiency',20,'test');const report=createReport('报告',b,r);b.metrics.gmv=9000000;assert.equal(report.baseline.metrics.gmv,1000000);assert.equal(report.note,'');assert.throws(()=>normalizeState({...emptyState(),selectedReportId:'missing'}));});
for(const audience of ['developer','operator','agent_internal',undefined])test('renderer blocks '+audience+' artifacts',()=>assert.equal(publicText({audience,visibility:'render',semantic_type:'product_copy',text:'secret internal'}),''));
for(const kind of ['implementation_constraint','eval_criterion','developer_note','reasoning','tool_envelope','debug_state','raw_protocol','internal_roadmap',undefined])test('renderer rejects '+kind,()=>assert.equal(publicText({audience:'user',visibility:'render',semantic_type:kind,text:'internal'}),''));
test('unknown/hidden content cannot render and allowed text is escaped',()=>{assert.equal(publicText({audience:'user',visibility:'never_render',semantic_type:'product_data',text:'hidden'}),'');assert.equal(publicText({audience:'user',visibility:'render',semantic_type:'product_data',text:'<img src=x onerror=alert(1)>'}),'&lt;img src=x onerror=alert(1)&gt;');});
test('report exports use a shared immutable source and escape human content',()=>{const report=createReport('<b>经营报告</b>',baseline());report.note='<script>alert(1)</script>';const html=reportHtml(report);assert.ok(html.includes('&lt;b&gt;经营报告&lt;/b&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('¥1,000,000'));assert.ok(html.includes('人工录入 · 尚未核验'));assert.ok(html.includes('打印 / 保存 PDF'));});
test('entry points include real modules, local export library and native accessible dialogs',()=>{const html=readFileSync('ui.html','utf8');for(const s of ['./src/ui-runtime.mjs','./src/vendor/pptxgen.bundle.js','<dialog id="sourceModal"','role="alert"','aria-live="polite"'])assert.ok(html.includes(s),s);for(const s of ['VERIFIED PERSISTED SOURCE','Reality boundary','原型内存状态','business-world-report.txt'])assert.ok(!html.includes(s),s);});

test('portable report round-trip preserves exact content and immutable source',()=>{const r=createReport('中文报告',baseline());r.note='人工备注';assert.deepEqual(readSharedReport(shareReportToken(r)),r);});
test('invalid portable report tokens fail closed',()=>{for(const x of ['<script>','invalid','','x'.repeat(64001)])assert.throws(()=>readSharedReport(x));});
