const workspace=document.querySelector('#workspace');
const dialog=document.querySelector('#run-dialog');
const dialogBody=document.querySelector('#run-dialog-body');
const toast=document.querySelector('.app-toast');
const steps=['产品设置','目标人群','市场环境','方案设计','运行设置'];
const state={step:0,scheme:'B',result:'summary',section:'lab',product:'白桃气泡水',category:'饮料',quarter:'2025 Q2',audience:'18–35 岁城市消费者',market:'华东线上市场',duration:90,running:false};
let toastTimer,runTimer;

const schemes={A:{price:6,channel:'小红书',message:'健康轻盈',sales:126,conversion:7.1,repeat:29,roi:2.1,color:'pink'},B:{price:8,channel:'小红书',message:'高级天然',sales:142,conversion:8.7,repeat:36,roi:2.8,color:'blue'},C:{price:8,channel:'抖音',message:'夏日解渴',sales:131,conversion:7.9,repeat:33,roi:2.5,color:'green'}};

function notify(message){clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('is-visible');toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2600);}
const selected=()=>schemes[state.scheme];
const e=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

function stepper(){return `<div class="experiment-stepper" role="tablist" aria-label="实验步骤">${steps.map((label,index)=>`<button role="tab" aria-selected="${state.step===index}" class="${state.step===index?'is-active':''}" data-step="${index}"><span>${index+1}</span>${label}</button>`).join('')}</div>`;}
function schemeCards(){return `<div class="scheme-header"><h3>实验方案（最多 3 个方案对比）</h3><button class="outline-button" data-action="add-scheme">＋ 添加方案</button></div><div class="scheme-grid">${Object.entries(schemes).map(([id,item])=>`<button class="scheme-card ${state.scheme===id?'is-selected':''}" data-scheme="${id}" aria-pressed="${state.scheme===id}"><span>方案 ${id}</span><strong>¥${item.price}</strong><small>${item.channel}<i class="dot ${item.color}"></i></small><small>${item.message}</small></button>`).join('')}</div>`;}

function productStep(){return `<div class="setup-grid"><section class="panel product-panel"><h3>产品信息</h3><div class="product-form"><div class="bottle" aria-label="白桃气泡水示意"><i>桃</i><span>气泡水</span></div><div class="fields"><label>产品名称<input data-field="product" value="${e(state.product)}"></label><label>产品描述<textarea rows="3">0 糖 0 脂、天然果味，年轻人的日常饮品选择。</textarea></label><div class="field-row"><label>产品类别<select data-field="category"><option selected>饮料</option><option>食品</option><option>个护</option></select></label><label>上市时间<select data-field="quarter"><option>2025 Q1</option><option selected>2025 Q2</option><option>2025 Q3</option></select></label></div></div></div></section><section class="panel schemes-panel">${schemeCards()}</section></div>`;}
function audienceStep(){return `<div class="setup-grid"><section class="panel form-panel"><span class="panel-kicker">目标人群</span><h3>谁会看到并购买这款产品？</h3><label>核心人群<input data-field="audience" value="${e(state.audience)}"></label><label>年龄范围<div class="range-value"><input type="range" min="18" max="55" value="35" data-action="age-range"><output>18–35 岁</output></div></label><fieldset><legend>生活方式标签</legend><div class="tag-picker"><button class="is-selected">健康生活</button><button class="is-selected">价格敏感</button><button>户外运动</button><button class="is-selected">社交活跃</button><button>精致育儿</button></div></fieldset></section><section class="panel audience-preview"><div class="large-avatar">林</div><h3>预计覆盖 100,000 个消费者 Agent</h3><p>样本人群会按年龄、城市、消费能力、兴趣与社交关系进行分层。</p><div><b>62%<small>女性</small></b><b>71%<small>一二线城市</small></b><b>48%<small>健康关注者</small></b></div></section></div>`;}
function marketStep(){return `<div class="setup-grid"><section class="panel form-panel"><span class="panel-kicker">市场环境</span><h3>定义产品进入的真实场景</h3><label>目标市场<input data-field="market" value="${e(state.market)}"></label><div class="field-row"><label>季节<select><option>春季</option><option selected>夏季</option><option>秋季</option></select></label><label>竞争强度<select><option>低</option><option selected>中</option><option>高</option></select></label></div><fieldset><legend>渠道</legend><div class="tag-picker"><button class="is-selected">小红书</button><button class="is-selected">抖音</button><button>天猫</button><button>线下便利店</button></div></fieldset></section><section class="panel market-map"><div class="map-orbit"><span>上海</span><i>杭州</i><b>南京</b><em>苏州</em></div><h3>华东城市消费网络</h3><p>示例环境包含渠道触点、竞争品牌与消费者社交扩散关系。</p></section></div>`;}
function designStep(){return `<section class="panel design-panel"><span class="panel-kicker">方案设计</span><h3>把变量放在同一张实验桌上</h3>${schemeCards()}<div class="comparison-table"><div><b>变量</b><b>方案 A</b><b>方案 B</b><b>方案 C</b></div><div><span>价格</span><span>¥6</span><span>¥8</span><span>¥8</span></div><div><span>传播渠道</span><span>小红书</span><span>小红书</span><span>抖音</span></div><div><span>核心信息</span><span>健康轻盈</span><span>高级天然</span><span>夏日解渴</span></div><div><span>视觉方向</span><span>清爽粉</span><span>高质蓝</span><span>活力绿</span></div></div></section>`;}
function runStep(){return `<div class="setup-grid"><section class="panel form-panel"><span class="panel-kicker">运行设置</span><h3>确认实验规模与周期</h3><label>仿真周期<div class="range-value"><input type="range" min="30" max="180" step="30" value="${state.duration}" data-action="duration"><output>${state.duration} 天</output></div></label><label>消费者 Agent 数量<select><option>10,000</option><option selected>100,000</option><option>500,000</option></select></label><label class="check-row"><input type="checkbox" checked> 启用社交关系扩散</label><label class="check-row"><input type="checkbox" checked> 启用竞品动态响应</label></section><section class="panel run-summary"><span class="panel-kicker">实验摘要</span><h3>${e(state.product)}</h3><dl><div><dt>目标人群</dt><dd>${e(state.audience)}</dd></div><div><dt>市场</dt><dd>${e(state.market)}</dd></div><div><dt>方案</dt><dd>A / B / C 并行对比</dd></div><div><dt>周期</dt><dd>${state.duration} 天</dd></div></dl><button class="primary-button run-button" data-action="run">开始仿真 →</button></section></div>`;}
function setupContent(){return [productStep,audienceStep,marketStep,designStep,runStep][state.step]();}

function lineChart(){return `<svg class="line-chart" viewBox="0 0 640 220" role="img" aria-label="三个方案的十二周销量趋势"><g class="grid-lines"><path d="M42 28H620M42 75H620M42 122H620M42 169H620"/><path d="M42 20V184M184 20V184M326 20V184M468 20V184M620 20V184"/></g><path class="line a" d="M42 178 184 145 326 109 468 76 620 45"/><path class="line b" d="M42 170 184 112 326 78 468 43 620 20"/><path class="line c" d="M42 184 184 163 326 139 468 111 620 82"/><g class="chart-labels"><text x="40" y="207">第 1 周</text><text x="175" y="207">第 3 周</text><text x="315" y="207">第 6 周</text><text x="455" y="207">第 9 周</text><text x="590" y="207">第 12 周</text></g></svg>`;}
function summaryResult(){const item=selected();return `<div class="result-grid"><section class="panel chart-card"><div class="card-title"><h3>销量趋势（累计）</h3><span class="legend"><i class="blue"></i>方案 B <i class="pink"></i>方案 A <i class="green"></i>方案 C</span></div>${lineChart()}</section><section class="panel bars-card"><h3>方案对比（关键指标）</h3><div class="metric-switch"><button class="is-active">销量</button><button>转化率</button><button>复购率</button><button>ROI</button></div><div class="bars"><button data-scheme="A" class="${state.scheme==='A'?'is-selected':''}"><b>126万</b><i class="pink" style="height:72%"></i><span>方案 A</span></button><button data-scheme="B" class="${state.scheme==='B'?'is-selected':''}"><b>142万</b><i class="blue" style="height:90%"></i><span>方案 B</span></button><button data-scheme="C" class="${state.scheme==='C'?'is-selected':''}"><b>131万</b><i class="green" style="height:78%"></i><span>方案 C</span></button></div></section></div><div class="insight-grid"><section class="panel consumer-card"><span class="panel-kicker">消费者视角</span><div class="consumer-head"><div class="profile-avatar">林</div><div><h3>林小雨 <small>25岁</small></h3><p>上海｜白领</p></div></div><blockquote>“这个 0 糖气泡水看起来很清爽，下次去便利店试试！”</blockquote><div class="tag-picker compact"><button>健康生活</button><button>价格敏感</button><button>社交活跃</button></div></section><section class="panel journey-card"><span class="panel-kicker">行为轨迹（示例）</span><ol><li><b>Day 1</b> 在小红书看到产品种草内容</li><li><b>Day 3</b> 搜索品牌并查看用户评论</li><li><b>Day 7</b> 在线购买（¥${item.price}）</li><li><b>Day 14</b> 分享购买体验</li><li><b>Day 28</b> 再次购买</li></ol></section><section class="panel network-card"><span class="panel-kicker">社交关系与影响</span><div class="network"><span class="network-main">林</span>${Array.from({length:8},(_,i)=>`<i style="--i:${i}">${'陈周李吴许赵孙钱'[i]}</i>`).join('')}</div><p>影响了 <b>12</b> 位好友<br>其中 <b>3</b> 位产生购买</p></section></div>`;}
function alternateResult(){const copy={audience:['人群分析','25–34 岁、上海与杭州的健康生活人群对“0 糖 + 天然果味”反应最强。'],market:['市场表现','方案 B 在第 6 周开始拉开差距，增长主要来自内容种草后的搜索与复购。'],social:['社交传播','核心用户平均影响 12 位好友，内容分享带来的间接购买占 18%。'],finance:['财务分析','方案 B 的预计 ROI 为 2.8，较行业平均 1.9 高 47%。'],compare:['对比洞察','方案 A 转化快但复购偏低；方案 C 传播广但客单价贡献较弱。']}[state.result];return `<section class="panel alternate-result"><div class="alternate-icon">✦</div><span class="panel-kicker">${copy[0]}</span><h3>${copy[1]}</h3><p>点击不同方案可查看同一维度下的结果变化。当前选中：方案 ${state.scheme}。</p><div class="evidence-bars"><span style="--value:88%">方案 B <b>88</b></span><span style="--value:74%">方案 C <b>74</b></span><span style="--value:69%">方案 A <b>69</b></span></div></section>`;}
function results(){const item=selected();const tabs=[['summary','总览'],['audience','人群分析'],['market','市场表现'],['social','社交传播'],['finance','财务分析'],['compare','对比洞察']];return `<section class="results"><div class="results-heading"><div><h2>仿真结果</h2><div class="result-tabs" role="tablist">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${state.result===id}" data-result="${id}" class="${state.result===id?'is-active':''}">${label}</button>`).join('')}</div></div><div><button class="outline-button" data-action="download">⇩ 下载报告</button><button class="outline-button" data-action="share">♧ 分享</button><select aria-label="选择实验"><option>实验：${e(state.product)}上市模拟</option></select></div></div><div class="kpi-grid"><article><span>预计销量（${state.duration}天）</span><strong>${item.sales*10000}<small> 瓶</small></strong><em>↑ ${state.scheme==='B'?18:state.scheme==='A'?11:14}%</em></article><article><span>购买转化率</span><strong>${item.conversion}%</strong><em>↑ 2.3%</em></article><article><span>复购率</span><strong>${item.repeat}%</strong><em>↑ 12%</em></article><article><span>社交传播人数</span><strong>${state.scheme==='B'?'1,200,000':'940,000'}</strong><em>↑ 448%</em></article><article><span>预计 ROI</span><strong>${item.roi}</strong><small>高于行业平均 1.9</small></article></div>${state.result==='summary'?summaryResult():alternateResult()}</section>`;}

function labView(){return `<div class="page-heading"><div><span class="panel-kicker">EXPERIMENT LAB</span><h1>新品上市模拟</h1><p>在线市场中模拟新产品的上市表现，支持多方案对比和长期影响分析。</p></div><button class="primary-button" data-action="run">开始仿真 →</button></div><section class="experiment panel">${stepper()}<div class="step-content">${setupContent()}</div><div class="step-actions"><button class="outline-button" data-action="previous" ${state.step===0?'disabled':''}>← 上一步</button><span>设置会自动保存在当前浏览器</span><button class="primary-button" data-action="next">${state.step===4?'运行实验':'保存并继续 →'}</button></div></section>${results()}`;}
function placeholderView(){const pages={home:['首页','查看最近实验和关键指标'],consumer:['消费者世界','探索人群画像与社交关系'],templates:['实验模板','从成熟场景快速开始'],mine:['我的实验','管理草稿、运行中和已完成实验'],market:['市场洞察','发现品类与人群变化'],data:['数据中心','管理实验所需的数据资产'],reports:['报告','查看并分享仿真证据'],settings:['设置','管理团队与实验偏好']};const [title,desc]=pages[state.section];return `<div class="page-heading"><div><span class="panel-kicker">WORLD AGENT</span><h1>${title}</h1><p>${desc}</p></div><button class="primary-button" data-nav="lab">返回实验中心 →</button></div><section class="panel empty-view"><div>✦</div><h2>${title}演示视图</h2><p>这个入口已经可以点击。当前交付重点是“新品上市模拟”的完整实验路径。</p><button class="primary-button" data-nav="lab">打开新品上市模拟</button></section>`;}
function render(){workspace.innerHTML=state.section==='lab'?labView():placeholderView();document.title=`${state.section==='lab'?'新品上市模拟':workspace.querySelector('h1')?.textContent} · World Agent`;}

function startRun(){clearInterval(runTimer);state.running=true;dialogBody.innerHTML=`<div class="run-progress"><span class="run-mark">W</span><span class="panel-kicker">WORLD AGENT</span><h2>正在运行 100,000 个消费者 Agent</h2><p>正在模拟认知、搜索、购买、分享与复购行为…</p><progress max="100" value="0"></progress><small>0%</small></div>`;dialog.showModal();let value=0;runTimer=setInterval(()=>{value+=20;const progress=dialogBody.querySelector('progress');if(!progress){clearInterval(runTimer);return;}progress.value=value;dialogBody.querySelector('small').textContent=`${value}%`;if(value===100){clearInterval(runTimer);state.running=false;dialogBody.innerHTML=`<div class="run-complete"><span>✓</span><h2>仿真完成</h2><p>方案 B 的综合表现最佳，预计销量 142 万瓶。</p><button class="primary-button" data-action="view-results">查看结果</button></div>`;}},280);}

document.addEventListener('click',event=>{
  const nav=event.target.closest('[data-nav]')?.dataset.nav;
  if(nav){state.section=nav;document.querySelectorAll('[data-nav]').forEach(button=>button.classList.toggle('is-active',button.dataset.nav===nav));document.body.classList.remove('nav-open');render();return;}
  const step=event.target.closest('[data-step]')?.dataset.step;if(step!==undefined){state.step=Number(step);render();return;}
  const scheme=event.target.closest('[data-scheme]')?.dataset.scheme;if(scheme){state.scheme=scheme;render();return;}
  const result=event.target.closest('[data-result]')?.dataset.result;if(result){state.result=result;render();return;}
  const tag=event.target.closest('.tag-picker button');if(tag){tag.classList.toggle('is-selected');return;}
  const action=event.target.closest('[data-action]')?.dataset.action;
  if(action==='next'){if(state.step<4){state.step++;render();}else startRun();}
  if(action==='previous'&&state.step>0){state.step--;render();}
  if(action==='run')startRun();
  if(action==='close-dialog'){clearInterval(runTimer);dialog.close();}
  if(action==='view-results'){dialog.close();document.querySelector('.results')?.scrollIntoView({behavior:'smooth'});notify('结果已更新为本次实验数据。');}
  if(action==='toggle-nav')document.body.classList.toggle('nav-open');
  if(action==='download')notify('演示报告已准备：正式版本将导出 PDF。');
  if(action==='share')notify('分享链接已复制（演示）。');
  if(action==='add-scheme')notify('当前演示已使用 3 个方案上限。');
});
document.addEventListener('input',event=>{
  const field=event.target.dataset.field;if(field)state[field]=event.target.value;
  if(event.target.dataset.action==='age-range'){event.target.nextElementSibling.value=`18–${event.target.value} 岁`;state.audience=`18–${event.target.value} 岁城市消费者`;}
  if(event.target.dataset.action==='duration'){state.duration=Number(event.target.value);event.target.nextElementSibling.value=`${state.duration} 天`;}
});
dialog.addEventListener('cancel',()=>clearInterval(runTimer));
render();
const route=location.hash.replace('#','');
if(route&&['product','pricing','creative','channel','market'].includes(route)){notify(`已按“${route}”场景打开新品上市实验。`);}
